language: php

php:
  - 7.4.3

before_script:
  - cp .env.travis .env
  - composer update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan jwt:secret
  - php artisan migrate


services:
  - mysql

notifications:
  email: false


