language: php

php:
  - 7.2

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install 
  - docker build -t laravelapp .

script:
  - vendor/bin/phpunit


